#!/usr/bin/env bash
# Configure, build and serve the WebAssembly build of EmptyEpsilon.
#
#   ./run-wasm.sh                 clean configure + build + serve on :8765
#   ./run-wasm.sh -i              keep the build directory (incremental)
#   ./run-wasm.sh -p 9000         serve on a different port
#   ./run-wasm.sh -n              build only, do not serve
#   ./run-wasm.sh -t Release      set CMAKE_BUILD_TYPE
#   ./run-wasm.sh -V 2026.8.11    pin the version (defaults to today's date)
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${SOURCE_DIR}/build-wasm"
EMSDK_DIR="${EMSDK_DIR:-${SOURCE_DIR}/local-reference/emsdk}"
SERIOUS_PROTON_DIR="${SERIOUS_PROTON_DIR:-${SOURCE_DIR}/local-reference/SeriousProton}"

port=8765
clean=1
serve=1
build_type=""
# The multiplayer handshake compares version numbers, and EmptyEpsilon derives
# its version from the configure date. Pin it to talk to a server that was
# built on a different day.
version="${EE_VERSION:-}"
jobs="$(nproc 2>/dev/null || echo 4)"

usage() {
    sed -n '2,9p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while getopts ":inp:t:j:V:h" opt; do
    case "${opt}" in
        i) clean=0 ;;
        n) serve=0 ;;
        p) port="${OPTARG}" ;;
        t) build_type="${OPTARG}" ;;
        V) version="${OPTARG}" ;;
        j) jobs="${OPTARG}" ;;
        h) usage 0 ;;
        :) echo "error: -${OPTARG} needs an argument" >&2; usage 1 ;;
        *) echo "error: unknown option -${OPTARG}" >&2; usage 1 ;;
    esac
done

if [ ! -f "${EMSDK_DIR}/emsdk_env.sh" ]; then
    cat >&2 <<EOF
error: no emscripten SDK at ${EMSDK_DIR}

Install it with:
    git clone --depth 1 https://github.com/emscripten-core/emsdk.git "${EMSDK_DIR}"
    "${EMSDK_DIR}/emsdk" install latest
    "${EMSDK_DIR}/emsdk" activate latest

Or point EMSDK_DIR at an existing installation.
EOF
    exit 1
fi

# emsdk_env.sh is chatty and not written with 'set -u' in mind.
set +u
# shellcheck disable=SC1091
source "${EMSDK_DIR}/emsdk_env.sh" >/dev/null 2>&1
set -u

if [ "${clean}" -eq 1 ]; then
    echo ">> removing ${BUILD_DIR}"
    rm -rf "${BUILD_DIR}"
fi

configure_args=(
    -G Ninja
    -B "${BUILD_DIR}"
    -S "${SOURCE_DIR}"
    -DSERIOUS_PROTON_DIR="${SERIOUS_PROTON_DIR}"
    # CMake can latch onto a stale git path and then fail to fetch GLM.
    -DGIT_EXECUTABLE="$(command -v git)"
)
[ -n "${build_type}" ] && configure_args+=(-DCMAKE_BUILD_TYPE="${build_type}")

if [ -n "${version}" ]; then
    IFS=. read -r v_major v_minor v_patch <<<"${version}"
    if [ -z "${v_patch:-}" ]; then
        echo "error: version must be MAJOR.MINOR.PATCH, got '${version}'" >&2
        exit 1
    fi
    # Strip leading zeroes so 2026.08.11 and 2026.8.11 mean the same thing.
    v_minor=$((10#${v_minor}))
    v_patch=$((10#${v_patch}))
    mkdir -p "${BUILD_DIR}"
    version_file="${BUILD_DIR}/ee-version.cmake"
    cat >"${version_file}" <<EOF
# Generated by run-wasm.sh, overrides the date-derived version.
set(PROJECT_VERSION ${v_major}.${v_minor}.${v_patch})
set(PROJECT_VERSION_MAJOR ${v_major})
set(PROJECT_VERSION_MINOR ${v_minor})
set(PROJECT_VERSION_PATCH ${v_patch})
set(EmptyEpsilon_VERSION \${PROJECT_VERSION})
set(EmptyEpsilon_VERSION_MAJOR ${v_major})
set(EmptyEpsilon_VERSION_MINOR ${v_minor})
set(EmptyEpsilon_VERSION_PATCH ${v_patch})
EOF
    configure_args+=(-DCMAKE_PROJECT_EmptyEpsilon_INCLUDE="${version_file}")
    echo ">> version pinned to ${v_major}.${v_minor}.${v_patch} (VERSION_NUMBER=$((v_major * 10000 + v_minor * 100 + v_patch)))"
else
    # Drop a pin left in the cache by an earlier -V run.
    configure_args+=(-UCMAKE_PROJECT_EmptyEpsilon_INCLUDE)
    rm -f "${BUILD_DIR}/ee-version.cmake"
fi

echo ">> configuring"
emcmake cmake "${configure_args[@]}"

echo ">> building with ${jobs} jobs"
cmake --build "${BUILD_DIR}" -j "${jobs}"

ls -la "${BUILD_DIR}"/EmptyEpsilon.{html,js,wasm,data}

if [ "${serve}" -eq 0 ]; then
    exit 0
fi

if command -v ss >/dev/null && ss -ltn "sport = :${port}" 2>/dev/null | grep -q LISTEN; then
    echo "error: port ${port} is already in use" >&2
    exit 1
fi

echo ">> serving http://localhost:${port}/EmptyEpsilon.html (ctrl-c to stop)"
echo ">> append #log to the URL for the in-page log overlay"
cd "${BUILD_DIR}"
exec python3 -m http.server "${port}"
